Feature/new build
sonr-io/nebula-react pull request #54
Opened 2022-05-19 15:56 UTC by gwelter

New Build without create-react-app

2022-05-19 20:18 UTC, joshLong145 commented
@ntindle builders seem to hanging on this pr are our builders down?

2022-05-19 20:57 UTC, ntindle requested changes
Dont commit .DS_store

2022-05-19 20:57 UTC, ntindle commented
Our builders don't "go down". It uses github actions. If the builder isn't running, it hasn't been triggered or GH is down

2022-05-19 20:59 UTC, ntindle commented
Try resolving the conflicts and see if it will run

2022-05-19 23:35 UTC, joshLong145 commented
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @sonr-io/nebula-react@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   dev react@"18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @storybook/react@6.4.22
npm ERR! node_modules/@storybook/react
npm ERR!   dev @storybook/react@"6.4.22" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/joshlong/.npm/eresolve-report.txt for a full report.
```
When I run `npm install` I get the following peer depedency conflictions, seems to be incompatibility with react 18 and storybook. perhaps we downgrade to 17 or 16

2022-05-19 23:35 UTC, joshLong145 commented
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: @sonr-io/nebula-react@0.1.0
> npm ERR! Found: react@18.1.0
> npm ERR! node_modules/react
> npm ERR!   dev react@"18.1.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.8.0 || ^17.0.0" from @storybook/react@6.4.22
> npm ERR! node_modules/@storybook/react
> npm ERR!   dev @storybook/react@"6.4.22" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /Users/joshlong/.npm/eresolve-report.txt for a full report.
> ```
> 
> When I run `npm install` I get the following peer depedency conflictions, seems to be incompatibility with react 18 and storybook. perhaps we downgrade to 17 or 16

Thinking about it, this is probably why the actions dont resolve, cant install the dependency tree and hangs up most likely.

2022-05-20 13:41 UTC, joshLong145 commented on package.json
> +    "react-dom": "^18.1.0"
Looks like we cannot target major version 18 in our repo as of this time due to storybook being incompatible. we should downgrade back to our previous version for compatibility

2022-05-20 17:32 UTC, gwelter commented on package.json
> +    "react-dom": "^18.1.0"
Downgraded to react 17.0.2 (@testing-library/react also since newer versions had react 18 as peer a dependency)

2022-05-20 17:40 UTC, joshLong145 approved these changes

2022-05-20 18:33 UTC, ntindle approved these changes

2022-05-20 18:34 UTC, merged